### ISSUE TITLE
Crash on mac os with message "string argument without an encoding"

### ISSUE THREAD

**Issue by haplm** [Plasmatree/PID-Analyzer#11]
I'm trying to run PID-Analyzer na on the latest MacOs (10.13.4), however, I'm getting following trace:

```
MartinH:PID-Analyzer haplm$ python3 PID-Analyzer.py --blackbox_decode ./blackbox_decode '-l /Users/haplm/Documents/BTFL_BLACKBOX_LOG_Tyrant_20180505_184347.BBL'
INFO 2018-05-06 16:47:42,793 PID-Analyzer.py:560: Decoding with '/Users/haplm/Development/PID-Analyzer/blackbox_decode'
INFO 2018-05-06 16:47:42,793 PID-Analyzer.py:562: PID-Analyzer 0.31
INFO 2018-05-06 16:47:42,793 PID-Analyzer.py:563: Hello Pilot!
Traceback (most recent call last):
  File "PID-Analyzer.py", line 567, in <module>
    run_analysis(clean_path(log_path), args.name, args.blackbox_decode)
  File "PID-Analyzer.py", line 524, in run_analysis
    test = BB_log(log_file_path, plot_name, blackbox_decode)
  File "PID-Analyzer.py", line 362, in __init__
    self.loglist = self.decode(log_file_path)
  File "PID-Analyzer.py", line 486, in decode
    first_newline_index = content.index(bytes('\n'))
TypeError: string argument without an encoding

```
blackbox_decode itself seems to be running fine:

```
MartinH:PID-Analyzer haplm$ ./blackbox_decode --simulate-current-meter /Users/haplm/Documents/BTFL_BLACKBOX_LOG_Tyrant_20180505_184347.BBL
Decoding log '/Users/haplm/Documents/BTFL_BLACKBOX_LOG_Tyrant_20180505_184347.BBL' to '/Users/haplm/Documents/BTFL_BLACKBOX_LOG_Tyrant_20180505_184347.01.csv'...

Log 1 of 2Statistics
E frames       2    8.0 bytes avg       16 bytes total
Frames        0
Data rate: Unknown, no timing information available.

1 iterations are missing in total (0ms, 100.00%)

Decoding log '/Users/haplm/Documents/BTFL_BLACKBOX_LOG_Tyrant_20180505_184347.BBL' to '/Users/haplm/Documents/BTFL_BLACKBOX_LOG_Tyrant_20180505_184347.02.csv'...

Log 2 of 2, start 00:39.777, end 03:08.594, duration 02:28.816

Statistics
Looptime            128 avg            7.5 std dev (5.8%)
I frames    4504   51.6 bytes avg   232315 bytes total
P frames  571875   25.2 bytes avg 14407977 bytes total
E frames       7    5.4 bytes avg       38 bytes total
S frames      78    8.0 bytes avg      624 bytes total
Frames    576379   25.4 bytes avg 14640292 bytes total
Data rate 3873Hz  98420 bytes/s     984300 baud

3 frames failed to decode, rendering 116 loop iterations unreadable. 116 iterations are missing in total (14ms, 0.01%)
576494 loop iterations weren't logged because of your blackbox_rate settings (74407ms, 50.00%)

```

**Comment by haplm** [comment]
[BTFL_BLACKBOX_LOG_Tyrant_20180505_184347.BBL.zip](https://github.com/Plasmatree/PID-Analyzer/files/1978887/BTFL_BLACKBOX_LOG_Tyrant_20180505_184347.BBL.zip)

And the log itself

**Comment by Plasmatree** [comment]
You are also using python3? 
Not sure if it's a mac or python3 problem. 
On win10/python2.7 I can't reproduce it. 
Seems to be a problem during log seperation, could be that binary encoding is handled differently. 
![btfl_blackbox_log_tyrant_20180505_184347tmp_0](https://user-images.githubusercontent.com/25606011/39803264-d63c7178-5370-11e8-99e4-45e165f27c69.png)

**Comment by haplm** [comment]
Yes, I was using python3. With 2.7 it runs fine, except this warning message:

INFO 2018-05-09 10:23:03,752 PID-Analyzer.py:308: Reading log 0...   
PID-Analyzer.py:364: DtypeWarning: Columns (35) have mixed types. Specify dtype option on import or set low_memory=False.
  self.figs = self._csv_iter(self.heads)

**Comment by Plasmatree** [comment]
Ah, great! 
Will address it in the next update.

**Comment by Plasmatree** [comment]
jep, but this does not work on 2.7.

**Comment by Plasmatree** [comment]
Fixed it in 0.4. 
Does this work for you?

**Comment by haplm** [comment]
No, now it fails in both 2.7 and 3:

Python 3:
```
MartinH:PID-Analyzer haplm$ python3 PID-Analyzer.py --blackbox_decode ../blackbox-tools/obj/blackbox_decode -l /Users/haplm/Documents/BTFL_BLACKBOX_LOG_Tyrant_20180512_195606.BBL 
Fontconfig warning: "/usr/local/etc/fonts/fonts.conf", line 146: blank doesn't take any effect anymore. please remove it from your fonts.conf
Fontconfig warning: ignoring UTF-8: not a valid region tag
INFO 2018-05-16 14:42:43,706 PID-Analyzer.py:865: Decoding with '/Users/haplm/Development/quads/blackbox-tools/obj/blackbox_decode'
INFO 2018-05-16 14:42:43,706 PID-Analyzer.py:867: PID-Analyzer 0.40
INFO 2018-05-16 14:42:43,706 PID-Analyzer.py:868: Hello Pilot!
Traceback (most recent call last):
  File "PID-Analyzer.py", line 872, in <module>
    run_analysis(clean_path(log_path), args.name, args.blackbox_decode)
TypeError: run_analysis() missing 1 required positional argument: 'show'
```

Python 2.7
```
MartinH:PID-Analyzer haplm$ python PID-Analyzer.py --blackbox_decode ../blackbox-tools/obj/blackbox_decode -l /Users/haplm/Documents/BTFL_BLACKBOX_LOG_Tyrant_20180512_195606.BBL 
INFO 2018-05-16 14:43:14,166 PID-Analyzer.py:865: Decoding with '/Users/haplm/Development/quads/blackbox-tools/obj/blackbox_decode'
INFO 2018-05-16 14:43:14,166 PID-Analyzer.py:867: PID-Analyzer 0.40
INFO 2018-05-16 14:43:14,166 PID-Analyzer.py:868: Hello Pilot!
Traceback (most recent call last):
  File "PID-Analyzer.py", line 872, in <module>
    run_analysis(clean_path(log_path), args.name, args.blackbox_decode)
TypeError: run_analysis() takes exactly 4 arguments (3 given)

```

I did this to update:
```
git pull
pip3 install -r requirements.txt
pip install -r requirements.txt
```

**Comment by haplm** [comment]
Fixing this is actually quite simple. Line 872 has to be changed to look like this:

`run_analysis(clean_path(log_path), args.name, args.blackbox_decode, args.show)`

**Comment by Plasmatree** [comment]
Ah, totally missed it. Thanks!

**Comment by trunglp** [comment]
@haplm 
i fix like 933 on version 0.5 but not working

if args.log:
        for log_path in args.log:
        run_analysis(clean_path(log_path), args.name, args.blackbox_decode, args.show)
            run_analysis(clean_path(log_path), args.name, args.blackbox_decode)
        if args.show.upper() == 'Y':
            plt.show()
        else:
            plt.cla()
           plt.clf()

The error 
LOG_20180512_171144.BBL 
  File "./PID-Analyzer.py", line 933
    run_analysis(clean_path(log_path), args.name, args.blackbox_decode, args.show)

----------------
MacBook-Pro:PID-Analyzer_old1 lptrung$ ./PID-Analyzer.py --blackbox_decode ./blackbox_decode -l BTFL_BLACKBOX_LOG_20180512_171144.BBL 
  File "./PID-Analyzer.py", line 933
    run_analysis(clean_path(log_path), args.name, args.blackbox_decode, args.show)
               ^
IndentationError: expected an indented block

**Comment by Plasmatree** [comment]
Looks like you changed the indentation by accident.

**Comment by haplm** [comment]
I think you can close this one, since couple versions back, everything works as expected. Thanks!
